# Generated by Django 4.2.14 on 2024-08-04 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_date_joined_alter_servicetype_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Experience_years must be between 1 and 99.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
