# Generated by Django 4.2.13 on 2024-06-10 13:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_providerprofile_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.service_seeker_image_file_path),
        ),
    ]
