# Generated by Django 4.2.13 on 2024-06-14 02:06

import core.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerprofile',
            old_name='city',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='name',
            new_name='service_type',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='certifications_documents',
            field=models.FileField(blank=True, null=True, upload_to=core.models.service_seeker_image_file_path),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.service_seeker_image_file_path),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating must be between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews_rating', to='core.providerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
