# Generated by Django 4.2.13 on 2024-06-18 14:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_city_providerprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='pricing_details',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='service_types',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='rate',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='provider',
            field=models.ManyToManyField(related_name='services', to='core.providerprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Rating must be between 1 and 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type',
            field=models.CharField(blank=True, choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('mechanic', 'Mechanic'), ('carpenter', 'Carpenter'), ('cleaner', 'Cleaner'), ('gardener', 'Gardener'), ('painter', 'Painter'), ('handyman', 'Handyman'), ('barber', 'Barber'), ('hairdresser', 'Hairdresser'), ('makeup_artist', 'Makeup Artist'), ('nail_technician', 'Nail Technician'), ('massage_therapist', 'Massage Therapist'), ('personal_trainer', 'Personal Trainer'), ('tutor', 'Tutor'), ('chef', 'Chef'), ('driver', 'Driver'), ('baby_sitter', 'Baby Sitter'), ('pet_sitter', 'Pet Sitter'), ('dog_walker', 'Dog Walker'), ('photographer', 'Photographer'), ('videographer', 'Videographer'), ('event_planner', 'Event Planner'), ('dj', 'DJ'), ('musician', 'Musician'), ('counselor', 'Counselor'), ('accountant', 'Accountant'), ('lawyer', 'Lawyer'), ('consultant', 'Consultant'), ('web_developer', 'Web Developer'), ('graphic_designer', 'Graphic Designer'), ('it_support', 'IT Support'), ('language_translator', 'Language Translator'), ('interior_designer', 'Interior Designer'), ('landscaper', 'Landscaper'), ('personal_assistant', 'Personal Assistant'), ('yoga_instructor', 'Yoga Instructor'), ('fitness_coach', 'Fitness Coach')], max_length=50, unique=True),
        ),
    ]
