# Generated by Django 4.2.13 on 2024-06-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_providerprofile_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='provider',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.providerprofile'),
        ),
    ]
