# Generated by Django 4.2.13 on 2024-06-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_servicetype_provider_servicetype_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='provider',
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews_rating', to='core.servicetype'),
        ),
    ]
